### ISSUE TITLE
Sharing error reports

### ISSUE THREAD

**Issue by jerneju** [axanthos/orange3-textable#3]
I am a member of Orange development team and one of my responsibilities is to find coding errors and remove bugs.

Orange Canvas application catches exceptions and when an user agree to send error report, the error information is sent to our web site.

On our site received reports are filtered and among them we also get those occurred by code from add-ons _textable_ and _textable-prototypes_.

We are eager to share reports with our add-on contributors. However if your team is wiling to participate you need to open a free account on a website https://sentry.io/. This website is designed for developers to help them monitor and fix crashes. I suggest you create two projects there. Each project for each of your _textable_ repositories (add-ons). Then you just need to send us a DSN key.

Regards.

**Comment by axanthos** [comment]
Sure, I have no experience with this platform but I'm happy to try it.

Can you please indicate (i) which of the DSN keys listed in the Client Keys tab of Sentry you need (the public one I guess?), and (ii) the email address to which I should send the keys?

Regards

**Comment by jerneju** [comment]
(i) DSN (not the public one)
(ii) jerneju@gmail.com

Regards

**Comment by axanthos** [comment]
Ok sent!
