### ISSUE TITLE
Extract XML with non alphanumeric symbol in XML element

### ISSUE THREAD

**Issue by darjusp** [axanthos/orange3-textable#4]
##### Textable version

3.0.6

##### Orange version

3.4.5

##### Expected behavior
Is there a way with extract XML to find xml elements by its name, if name consist of at least one non letter or number, for example dast(-). 
If element name is, lets say, `<scopus>` it will locate all entities, if its `<scopus-id>` it will locate none

##### Actual behavior
please look at the attachment.
If asked to extract "scopus", which is only a part of full needed element, then we get 4 elements, but if asked to extract  "scopus-id", which is full name of element, then we get 0. I feel its because search process breaks after finding dash in between.

##### Steps to reproduce the behavior
Here is the excerpt from the XML file I was using

```xml
<reference id="1">
<sourcetitle>Nothing important</sourcetitle>
<pubmed-id>5345491</pubmed-id>
<scopus-id>0014608620</scopus-id>
<scopus-eid>2-s2.0-0014608620</scopus-eid>
</reference>
<reference id="2">
<sourcetitle>Acta Dermato-Venereologica</sourcetitle>
<pubmed-id>46678</pubmed-id>
<scopus-id>0016663636</scopus-id>
<scopus-eid>2-s2.0-0016663636</scopus-eid>
</reference>
```
##### Additional info (worksheets, data, screenshots, ...)

![screen shot 2017-10-13 at 12 19 38](https://user-images.githubusercontent.com/10597360/31544147-157f352a-b022-11e7-982f-abad044a3c2b.png)

**Comment by axanthos** [comment]
Thanks for this feedback. Issue was due to incorrect definition of xml token in underlying LTTL library and has been fixed in LTTL v2.0.6 (just released). Can you please update LTTL (using pip for example) and confirm if everything works as expected?

**Comment by darjusp** [comment]
Hi, thanks for the reply. I just updated it. I checked the version in the terminal and it seems updated:
pip freeze | grep LTTL
LTTL==2.0.6

I tried again the example, but result is the same, - not recognized. I'm using Mac OS and Orange 3 as a standalone application, not within Anaconda. Is there a way to check what version of LTTL Orange 3 is using?

**Comment by axanthos** [comment]
On MacOS, Orange uses its own Python distribution. In principle it is located here: /Applications/Orange3.app/Contents/MacOS/pip. You can use freeze and install options as usual (possibly with sudo).

**Comment by darjusp** [comment]
Excellent, that was the case, I updated with Orange PIP and now it processing xml correctly.
Thank you very much for your help.

**Comment by axanthos** [comment]
Thanks for your feedback and confirmation.
